# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archive:
    text: 档案
    url: /archives/
  tags:
    text: 标签
    url: /tags/
  th-list:
    text: 分类
    url: /categories/
  id-card-o:
    text: 关于
    url: /about/

# 你的头像url
avatar: /static/img/img.png
# avatar link
avatar_link: /
# favicon
favicon: /favicon.ico

# ----------------------------------------------menu底部四个图标设置start
# 链接+fontawesome图标代号(去除fa-)
menuBottom:
  https://github.com/xizirumeng: github-alt
  https://twitter.com/xizirumeng: twitter-square
  mailto:xizirumeng@foxmail.com: envelope
  http://wpa.qq.com/msgrd?v=3&uin=201269807&site=oicqzone.com&menu=yes: qq
# ----------------------------------------------menu底部四个图标设置end

# ----------------------------------------------友情链接start
# 链接+标题
links:
  https://bidd.net: 今生唯梦
  https://gao4.pw: 沫雨
  http://joahcy.com: Joahcy
# ----------------------------------------------友情链接end

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#4d4d4d'

# 页面标题
tags_title: 标签
archives_title: 档案
categories_title: 分类
photos_title: 相册

# 文章截断
excerpt_render: true
excerpt_length: 500
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: false

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward: false
#  title: 赠人玫瑰 手留余香~~
#  wechat: /static/img/wechat.jpg     #微信，关闭设为 false
#  alipay: /static/img/alipay.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 转载请注明出处：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 百度主动推送
baidu_push: true

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/static/css/style.less

# 是否开启评论
comments: true

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: https://bidd.net

# 版权起始年份
since_year: 2016

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 避不开的梦，躲不过的劫

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：
#visit_counter: false

# 动态定义title
title_change:
  normal: 遨游四海求其凰
  leave: 凤兮凤兮归故乡

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: 湘ICP备18010960

# 公安备案
PS_license:
  code: 43060202000266
  content: 湘公网安备 43060202000266号
# 背景音乐
# 路径或者false
music: /static/music/ksxf.mp3